import { Category } from '../../constants.js';
import { CollectionDescriptor } from '../../struct.js';

const HELM: CollectionDescriptor = {
  name: 'Helm',
  category: Category.ARMOR,
  items: [
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_028Crafted_L27.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_056.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_050.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_051.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Magic_Generic_025Crafted.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_Crafted044.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_003_BlackSabbath.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_030Crafted_L39.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_029Crafted_L33.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Magic_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_054.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_053.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_055.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Normal_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_027Crafted_L21.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Legendary_Generic_052.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Rare_Generic_Crafted026.itm.json'],
    // expansion
    ['json\\base\\meta\\Item\\Helm_Normal_Generic_010.itm.json'],
    ['json\\base\\meta\\Item\\X1_QST_Helm_Legendary_Generic_HatredSet.itm.json'],
    ['json\\base\\meta\\Item\\X1_Helm_Cosmetic_Urivar.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Normal_Generic_011.itm.json'],
    ['json\\base\\meta\\Item\\X1_QST_Helm_Legendary_Generic_013.itm.json'],
    // uniques
    ['json\\base\\meta\\Item\\S05_BSK_Helm_Unique_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Unique_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\Helm_Unique_Generic_004.itm.json'],
  ],
};

const CHEST_ARMOR: CollectionDescriptor = {
  name: 'Chest Armor',
  category: Category.ARMOR,
  items: [
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_Crafted028.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_056.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_050.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_051.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Magic_Generic_Crafted025.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_Crafted044.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_003_BlackSabbath.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_Crafted030.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_Crafted029.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Normal_Generic_009.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_Crafted026.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Magic_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_054.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_053.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_055.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Normal_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_Crafted027.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Any_Generic_001_Gambling_PvP.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Legendary_Generic_052.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Rare_Generic_004.itm.json'],
    // expansion
    ['json\\base\\meta\\Item\\X1_QST_Chest_Legendary_Generic_HatredSet.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Normal_Generic_011.itm.json'],
    ['json\\base\\meta\\Item\\X1_QST_Chest_Legendary_Generic_013.itm.json'],
    // unique
    ['json\\base\\meta\\Item\\Chest_Unique_Rogue_101.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Unique_Generic_127.itm.json'],
    ['json\\base\\meta\\Item\\Chest_Unique_Generic_103.itm.json'],
  ],
};

const GLOVES: CollectionDescriptor = {
  name: 'Gloves',
  category: Category.ARMOR,
  items: [
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_Crafted028.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_056.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_050.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_051.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Magic_Generic_025Crafted.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_Crafted044.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Magic_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_Crafted030.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Normal_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_Crafted029.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Normal_Generic_009.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_054.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_Crafted026.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_053.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_055.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Normal_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_Crafted027.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Legendary_Generic_052.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Rare_Generic_004.itm.json'],
    // expansion
    ['json\\base\\meta\\Item\\X1_QST_Gloves_Legendary_Generic_HatredSet.itm.json'],
    ['json\\base\\meta\\Item\\X1_QST_Gloves_Legendary_Generic_013.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Normal_Generic_010.itm.json'],
    // unique
    ['json\\base\\meta\\Item\\Gloves_Unique_Druid_100.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Unique_Barb_100.itm.json'],
    ['json\\base\\meta\\Item\\Gloves_Unique_Necro_101.itm.json'],
    ['json\\base\\meta\\Item\\S05_BSK_Gloves_Unique_Generic_001.itm.json'],
  ],
};

const PANTS: CollectionDescriptor = {
  name: 'Pants',
  category: Category.ARMOR,
  items: [
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_028Crafted_L25.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_056.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_050.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_Crafted026.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_051.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Magic_Generic_025Crafted.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_Crafted044.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_030Crafted_L35.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_029Crafted_L29.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Normal_Generic_009.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Normal_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Magic_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_054.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_053.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_055.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Normal_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_027Crafted_L19.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Legendary_Generic_052.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Rare_Generic_004.itm.json'],
    // expansion
    ['json\\base\\meta\\Item\\X1_QST_Pants_Legendary_Generic_013.itm.json'],
    // unique
    ['json\\base\\meta\\Item\\Pants_Unique_Barb_100.itm.json'],
    ['json\\base\\meta\\Item\\Pants_Unique_Sorc_101.itm.json'],
  ],
};

const BOOTS: CollectionDescriptor = {
  name: 'Boots',
  category: Category.ARMOR,
  items: [
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_028Crafted_L23.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_056.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_050.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_Crafted026.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_051.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Magic_Generic_025Crafted.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_Crafted044.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_003_BlackSabbath.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_030Crafted_L35.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_029Crafted_L29.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Normal_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Normal_Generic_009.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_054.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_053.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_055.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Normal_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_027Crafted_L17.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Magic_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Legendary_Generic_052.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Rare_Generic_004.itm.json'],
    // expansion
    ['json\\base\\meta\\Item\\X1_QST_Boots_Legendary_Generic_HatredSet.itm.json'],
    ['json\\base\\meta\\Item\\X1_QST_Boots_Legendary_Generic_013.itm.json'],
    // unique
    ['json\\base\\meta\\Item\\Boots_Unique_Rogue_100.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Unique_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\S05_BSK_Boots_Unique_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\Boots_Unique_Necro_101.itm.json'],
  ],
};

const ARMOR: CollectionDescriptor = {
  name: 'Armor',
  description: 'Transmogs found throughout sanctuary',
  category: Category.GENERAL,
  children: [HELM, CHEST_ARMOR, GLOVES, PANTS, BOOTS],
};

export default ARMOR;
