import { Category } from '../../constants.js';
import { CollectionDescriptor } from '../../struct.js';

const TWO_HANDED_AXE: CollectionDescriptor = {
  name: 'Two-Handed Axe',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HAxe_Rare_Generic_006_Rare.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Rare_Generic_005_Rare.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Magic_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Rare_Generic_004_Rare.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Rare_Druid_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Rare_Barb_Crafted_47.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Rare_Barb_Crafted_43.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Rare_Barb_Crafted_25.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Magic_Barb_Crafted_9.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HAxe_Unique_Barb_001.itm.json'],
  ],
};

const TWO_HANDED_MACE: CollectionDescriptor = {
  name: 'Two-Handed Mace',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HMace_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Barb_Crafted_27.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Barb_Crafted_31.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Barb_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Druid_Crafted_45.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Barb_Crafted_35.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Rare_Barb_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Unique_Barb_001.itm.json'],
    ['json\\base\\meta\\Item\\2HMace_Unique_Barb_100.itm.json'],
  ],
};

const TWO_HANDED_SWORD: CollectionDescriptor = {
  name: 'Two-Handed Sword',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HSword_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Magic_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Barb_Crafted_15.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Necro_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Barb_Crafted_33.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Rare_Necro_Crafted_31.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Unique_Barb_002.itm.json'],
    ['json\\base\\meta\\Item\\2HSword_Unique_Generic_001.itm.json'],
  ],
};

const TWO_HANDED_SCYTHE: CollectionDescriptor = {
  name: 'Two-Handed Scythe',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HScythe_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_006.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_003.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_Crafted_19.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_004.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_005.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_Crafted_11.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_Crafted_47.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_Crafted_43.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Rare_Necro_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\2HScythe_Unique_Necro_100.itm.json'],
  ],
  patches: [
    {
      items: [1307041],
      unobtainable: true,
    },
    {
      items: [1307043],
      unobtainable: true,
    },
  ],
};

const POLEARM: CollectionDescriptor = {
  name: 'Polearm',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HPolearm_Normal_Barb_000.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_Crafted_29.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_004.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_006.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_005.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_003.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_002.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Normal_Barb_Crafted_5.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_Crafted_45.itm.json'],
    ['json\\base\\meta\\Item\\2HPolearm_Rare_Barb_Crafted_37.itm.json'],
  ],
  patches: [
    {
      items: [592304],
      unobtainable: true,
    },
  ],
};

const SCYTHE: CollectionDescriptor = {
  name: 'Scythe',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_005.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Magic_Necro_001.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_004.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_002.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Normal_Necro_000.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_006.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_Crafted_41.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Rare_Necro_Crafted_21.itm.json'],
    ['json\\base\\meta\\Item\\1HScythe_Legendary_Generic_004.itm.json'],
  ],
  patches: [
    {
      items: [1307028],
      unobtainable: true,
    },
  ],
};

const SWORD: CollectionDescriptor = {
  name: 'Sword',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Barb_Crafted_23.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Rogue_Crafted_47.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Barb_Crafted_43.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Necro_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Rare_Barb_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Unique_Generic_100.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Unique_Barb_101.itm.json'],
    ['json\\base\\meta\\Item\\S05_BSK_1HSword_uniq16_TransmogItem.itm.json'],
    ['json\\base\\meta\\Item\\1HSword_Unique_Generic_001.itm.json'],
  ],
};

const AXE: CollectionDescriptor = {
  name: 'Axe',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HAxe_Rare_Barb_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Barb_Crafted_31.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Barb_Crafted_47.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Barb_Crafted_25.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Rare_Barb_Crafted_15.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Magic_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Unique_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HAxe_Unique_Druid_100.itm.json'],
  ],
  patches: [
    {
      items: [459950],
      unobtainable: true,
    },
    {
      items: [459949],
      unobtainable: true,
    },
    {
      items: [784817],
      unobtainable: true,
    },
    {
      items: [459948],
      unobtainable: true,
    },
    {
      items: [1046306],
      unobtainable: true,
    },
    {
      items: [1267098],
      unobtainable: true,
    },
    {
      items: [1306998],
      unobtainable: true,
    },
  ],
};

const MACE: CollectionDescriptor = {
  name: 'Mace',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Druid_Crafted_19.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Druid_Crafted_11.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Barb_Crafted_45.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Barb_Crafted_41.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Barb_Crafted_33.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Rare_Barb_Crafted_27.itm.json'],
    ['json\\base\\meta\\Item\\1HMace_Unique_Druid_001.itm.json'],
  ],
  patches: [
    {
      items: [784853],
      unobtainable: true,
    },
    {
      items: [784740],
      unobtainable: true,
    },
    {
      items: [459997],
      unobtainable: true,
    },
    {
      items: [459996],
      unobtainable: true,
    },
  ],
};

const SHIELD: CollectionDescriptor = {
  name: 'Shield',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HShield_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Necro_Crafted_13.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Necro_Crafted_29.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Magic_Necro_Crafted_10.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Barb_Crafted_47.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Necro_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Necro_Crafted_21.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HShield_Unique_Necro_100.itm.json'],
  ],
  patches: [
    {
      items: [1307045],
      unobtainable: true,
    },
  ],
};

const CROSSBOW: CollectionDescriptor = {
  name: 'Crossbow',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Rare_Rogue_Crafted_17.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Rare_Rogue_Crafted_25.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Magic_Rogue_Crafted_9.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Rare_Rogue_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Rare_Rogue_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Rare_Rogue_Crafted_33.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\2HCrossbow_Legendary_Generic_002.itm.json'],
  ],
  patches: [
    {
      items: [1267257],
      unobtainable: true,
    },
  ],
};

const BOW: CollectionDescriptor = {
  name: 'Bow',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HBow_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Magic_Rogue_001.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_Crafted_29.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_006.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_Crafted_13.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_Crafted_21.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Normal_Rogue_000.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_005.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Normal_Rogue_Crafted_5.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_Crafted_37.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_Crafted_41.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Rare_Rogue_Crafted_45.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Unique_Rogue_100.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Unique_Rogue_006.itm.json'],
    ['json\\base\\meta\\Item\\2HBow_Unique_Rogue_001.itm.json'],
  ],
  patches: [
    {
      items: [1267248],
      unobtainable: true,
    },
  ],
};

const DAGGER: CollectionDescriptor = {
  name: 'Dagger',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Magic_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Rogue_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Rogue_Crafted_35.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Rogue_Crafted_19.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Rogue_Crafted_43.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_010.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Legendary_Generic_009.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Unique_Rogue_002.itm.json'],
    ['json\\base\\meta\\Item\\1HDagger_Unique_Rogue_001.itm.json'],
    ['json\\base\\meta\\Item\\S05_BSK_1HDagger_uniq17_TransmogItem.itm.json'],
  ],
  patches: [
    {
      items: [459944],
      unobtainable: true,
    },
    {
      items: [1267078],
      unobtainable: true,
    },
    {
      items: [1267003],
      unobtainable: true,
    },
  ],
};

const STAFF: CollectionDescriptor = {
  name: 'Staff',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_15.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_23.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_008.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorcerer_002.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_006.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_009.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_002.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_27.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_004.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_007.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_005.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_003.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorcerer_006.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorcerer_005.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Normal_Sorc_Crafted_7.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_31.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_47.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_35.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_43.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Sorc_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Druid_005.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Druid_004.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Druid_003.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Druid_002.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_012.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Sorcerer_011.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Druid_006.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Druid_005.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Druid_004.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Druid_003.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Legendary_Druid_001.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Rare_Druid_006.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Unique_Sorc_100.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Unique_Sorc_002.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Unique_Druid_001.itm.json'],
    ['json\\base\\meta\\Item\\S05_BSK_2HStaff_uniq11_TransmogItem.itm.json'],
    ['json\\base\\meta\\Item\\2HStaff_Unique_Generic_100.itm.json'],
  ],
  patches: [
    {
      items: [1306653],
      unobtainable: true,
    },
    {
      items: [1306651],
      unobtainable: true,
    },
    {
      items: [1306958],
      unobtainable: true,
    },
    {
      items: [1306956],
      unobtainable: true,
    },
  ],
};

const WAND: CollectionDescriptor = {
  name: 'Wand',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HWand_Magic_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Necro_Crafted_25.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Normal_Generic_Crafted_5.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Necro_Crafted_17.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Sorc_Crafted_41.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Sorc_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Sorc_Crafted_37.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Sorc_Crafted_33.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Rare_Sorc_Crafted_45.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Legendary_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Unique_Sorc_101.itm.json'],
    ['json\\base\\meta\\Item\\1HWand_Unique_Sorc_100.itm.json'],
  ],
  patches: [
    {
      items: [1266266],
      unobtainable: true,
    },
  ],
};

const FOCUS: CollectionDescriptor = {
  name: 'Focus',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HFocus_Rare_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Generic_006.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_008.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_005.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_007.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_002.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Normal_Generic_000.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_004.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_001.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Legendary_Generic_003.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_45.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_41.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_29.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_21.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_17.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_13.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Sorc_Crafted_37.itm.json'],
    ['json\\base\\meta\\Item\\1HFocus_Rare_Necro_Crafted_25.itm.json'],
  ],
  patches: [
    {
      items: [459859],
      unobtainable: true,
    },
    {
      items: [459857],
      unobtainable: true,
    },
  ],
};

const TOTEM: CollectionDescriptor = {
  name: 'Totem',
  category: Category.WEAPON,
  items: [
    ['json\\base\\meta\\Item\\1HTotem_Normal_Druid_000.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_39.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_43.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_49.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_23.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_27.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_31.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Rare_Druid_Crafted_35.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Legendary_Druid_001.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Legendary_Druid_002.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Legendary_Druid_003.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Legendary_Druid_004.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Legendary_Druid_005.itm.json'],
    ['json\\base\\meta\\Item\\1HTotem_Magic_Druid_001.itm.json'],
  ],
  patches: [
    {
      items: [1267242],
      unobtainable: true,
    },
  ],
};

const WEAPON: CollectionDescriptor = {
  name: 'Weapon',
  description: 'Transmogs found throughout sanctuary',
  category: Category.GENERAL,
  children: [
    TWO_HANDED_AXE,
    TWO_HANDED_MACE,
    TWO_HANDED_SWORD,
    TWO_HANDED_SCYTHE,
    POLEARM,
    SCYTHE,
    SWORD,
    AXE,
    MACE,
    SHIELD,
    CROSSBOW,
    BOW,
    DAGGER,
    STAFF,
    WAND,
    FOCUS,
    TOTEM,
  ],
};

export default WEAPON;
